use super::super::super::dto::config_global_dto::ConfigGlobalDTO;
use crate::commands::command_trait::cmd_trait::CliCommand;
use clap::{Arg, ArgAction, Command};
use colored::*;

pub struct CommandPattern;

impl CliCommand for CommandPattern {

    fn arg() -> Arg {
        Arg::new("pattern")
            .long("pattern")
            .short('p')
            .action(ArgAction::SetTrue)
            .help("Displays detailed pattern for the Nidus CLI.")
    }

    fn command() -> Command {
        Command::new("pattern").about("📐 Show the Nidus architectural pattern reference")
    }

    fn execute(_global_dto: &mut ConfigGlobalDTO, _matches: &clap::ArgMatches) {
        let print_text: Vec<String> = vec![
            "".to_string(),
            "📐 Structural Pattern - Nidus CLI + Nidus".to_string(),
            "────────────────────────────────────────────".to_string(),
            "".to_string(),
            "1. Module Layer (<module>.module.pas)".to_string(),
            "   • Responsible for registering the module's dependencies (binds).".to_string(),
            "   • Defines which controllers, services, and interfaces will be used.".to_string(),
            "   • Used by Nidus for dependency injection and component lifecycle.".to_string(),
            "".to_string(),
            "2. Router Layer (<module>.routes.pas)".to_string(),
            "   • Defines the HTTP endpoints and verbs (GET, POST, etc).".to_string(),
            "   • Routes incoming requests to the appropriate controllers.".to_string(),
            "".to_string(),
            "3. Controller Layer (<module>.controller.pas)".to_string(),
            "   • Handles external requests and invokes the services.".to_string(),
            "   • Contains only routing logic between input and output.".to_string(),
            "   • Must not contain business logic.".to_string(),
            "".to_string(),
            "4. Service Layer (<module>.service.pas)".to_string(),
            "   • Contains all the application’s business logic.".to_string(),
            "   • Orchestrates calls to repositories, validations, and integrations.".to_string(),
            "   • It is the main business logic layer of the application.".to_string(),
            "".to_string(),
            "5. Repository Layer (<module>.repository.pas)".to_string(),
            "   • Responsible for data access and persistence.".to_string(),
            "   • May use ORM, REST APIs, files, etc.".to_string(),
            "   • Directly consumed by the services.".to_string(),
            "".to_string(),
            "6. Interface Layer (<module>.interface.pas)".to_string(),
            "   • Defines contracts for data access or external services.".to_string(),
            "   • Implemented by the Infrastructure layer.".to_string(),
            "   • Facilitates mocking in tests and promotes low coupling.".to_string(),
            "".to_string(),
            "7. Infrastructure Layer (<module>.infra.pas)".to_string(),
            "   • Implements the interfaces defined in the previous layer.".to_string(),
            "   • May include integration code with REST, files, sockets, etc.".to_string(),
            "   • Contains technical code, separate from domain logic.".to_string(),
            "".to_string(),
            "🌐 Default structure generated by Nidus CLI:".to_string(),
            "   src/".to_string(),
            "   ├── app.server.pas".to_string(),
            "   ├── app.module.pas".to_string(),
            "   ├── app.route.pas".to_string(),
            "   └── modules/".to_string(),
            "       └── <module>/".to_string(),
            "           ├── <module>.controller.pas".to_string(),
            "           ├── <module>.service.pas".to_string(),
            "           ├── <module>.repository.pas".to_string(),
            "           ├── <module>.interface.pas".to_string(),
            "           ├── <module>.infra.pas".to_string(),
            "           ├── <module>.module.pas".to_string(),
            "           └── <module>.routes.pas".to_string(),
            "".to_string(),
            "✅ Use the command: Nidus gen module <name>".to_string(),
            "".to_string(),
        ];

        println!("{}", print_text.join("\n").yellow());
    }
}
