use super::command_trait::cmd_trait::CliCommand;
use super::super::dto::config_global_dto::ConfigGlobalDTO;
use clap::{Arg, ArgAction, Command};
use colored::*;
use std::path::{Path, PathBuf};

/// Returns true if the path is tracked by git (staged or committed).
fn is_git_tracked(path: &Path) -> bool {
    // Walk up to find the git repo root
    let repo = match git2::Repository::discover(path) {
        Ok(r) => r,
        Err(_) => return false,
    };
    let workdir = match repo.workdir() {
        Some(d) => d,
        None => return false,
    };
    let relative = match path.strip_prefix(workdir) {
        Ok(r) => r,
        Err(_) => return false,
    };
    // Check HEAD tree + index
    let in_index = repo.index().map(|idx| idx.get_path(relative, 0).is_some()).unwrap_or(false);
    if in_index {
        return true;
    }
    // Check HEAD commit tree
    repo.head()
        .ok()
        .and_then(|h| h.peel_to_commit().ok())
        .and_then(|c| c.tree().ok())
        .and_then(|tree| tree.get_path(relative).ok())
        .is_some()
}

/// File extensions compiled by Delphi that can be safely removed
const DELPHI_EXTENSIONS: &[&str] = &[
    "dcu", "dcp", "bpl", "bpi", "drc", "map", "dsk", "identcache", "tvsconfig",
];

/// Directories generated by Delphi builds / IDE that can be safely removed
const DELPHI_BUILD_DIRS: &[&str] = &[
    "Win32", "Win64", "OSX32", "OSX64",
    "Android", "iOSDevice32", "iOSDevice64", "iOSSimulator",
    "__history", "__recovery",
];

pub struct CommandClean;

impl CliCommand for CommandClean {
    fn arg() -> Arg {
        Arg::new("")
    }

    fn command() -> Command {
        Command::new("clean")
            .about("🧹 Remove Delphi build artifacts (*.dcu, Win32/, __history/, …)")
            .long_about(
                "Scans the current directory tree for Delphi compilation artifacts\n\
                 and lists them. Pass --execute to actually delete them.\n\n\
                 Removes:\n  \
                 • Compiled units (.dcu, .dcp, .bpl, .bpi, .drc, .map …)\n  \
                 • Build output dirs (Win32/, Win64/, OSX32/ …)\n  \
                 • IDE history dirs (__history/, __recovery/)\n\n\
                 Files tracked by git are never deleted.",
            )
            .arg(
                Arg::new("execute")
                    .long("execute")
                    .short('x')
                    .action(ArgAction::SetTrue)
                    .help("Actually delete the artifacts (default is dry-run)"),
            )
            .arg(
                Arg::new("path")
                    .long("path")
                    .value_name("DIR")
                    .help("Directory to scan (default: current directory)"),
            )
            .arg(
                Arg::new("yes")
                    .long("yes")
                    .short('y')
                    .action(ArgAction::SetTrue)
                    .help("Skip confirmation prompt when --execute is used"),
            )
    }

    fn execute(_global_dto: &mut ConfigGlobalDTO, matches: &clap::ArgMatches) {
        let execute = matches.get_flag("execute");
        let yes = matches.get_flag("yes");
        let root = matches
            .get_one::<String>("path")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));

        let (files, dirs) = collect_artifacts(&root);
        let total_files = files.len();
        let total_dirs = dirs.len();

        if total_files == 0 && total_dirs == 0 {
            println!("{}", "\n✅ Nothing to clean — no Delphi artifacts found.\n".green());
            return;
        }

        println!("{}", "\n🧹 Delphi artifacts found:\n".bold().cyan());

        if !dirs.is_empty() {
            println!("{}", "  Directories:".bold());
            for d in &dirs {
                println!("    🗂  {}", d.display());
            }
        }
        if !files.is_empty() {
            println!("{}", "  Files:".bold());
            for f in &files {
                println!("    📄  {}", f.display());
            }
        }

        println!(
            "\n  {} {} file(s) and {} director(ies)\n",
            "Total:".bold(),
            total_files.to_string().yellow(),
            total_dirs.to_string().yellow(),
        );

        if !execute {
            println!(
                "{}",
                "💡 Dry-run mode — pass --execute to delete these items.".dimmed()
            );
            println!();
            return;
        }

        // Confirmation prompt unless --yes
        if !yes {
            print!("  Delete all listed items? [y/N] ");
            let _ = std::io::Write::flush(&mut std::io::stdout());
            let mut answer = String::new();
            std::io::stdin().read_line(&mut answer).ok();
            if !answer.trim().eq_ignore_ascii_case("y") {
                println!("{}", "  Aborted.".dimmed());
                println!();
                return;
            }
        }

        let mut removed_files = 0usize;
        let mut removed_dirs = 0usize;
        let mut failed = 0usize;

        // Remove directories first (recursively)
        for d in &dirs {
            match std::fs::remove_dir_all(d) {
                Ok(_) => {
                    println!("  {} {}", "🗑  Removed dir:".green(), d.display());
                    removed_dirs += 1;
                }
                Err(e) => {
                    eprintln!("  {} {}: {}", "⚠️  Failed:".yellow(), d.display(), e);
                    failed += 1;
                }
            }
        }

        // Remove individual files
        for f in &files {
            match std::fs::remove_file(f) {
                Ok(_) => {
                    println!("  {} {}", "🗑  Removed:".green(), f.display());
                    removed_files += 1;
                }
                Err(e) => {
                    eprintln!("  {} {}: {}", "⚠️  Failed:".yellow(), f.display(), e);
                    failed += 1;
                }
            }
        }

        println!();
        println!("{}", "🎯 Clean summary".bold().cyan());
        println!("  {} {}", "Files removed: ".bold(), removed_files.to_string().green());
        println!("  {} {}", "Dirs removed:  ".bold(), removed_dirs.to_string().green());
        if failed > 0 {
            println!("  {} {}", "Failed:        ".bold(), failed.to_string().red());
        }
        println!();
    }
}

/// Recursively collects Delphi build artifacts under `root`.
/// Returns `(files, directories)`.
fn collect_artifacts(root: &Path) -> (Vec<PathBuf>, Vec<PathBuf>) {
    let mut files: Vec<PathBuf> = Vec::new();
    let mut dirs: Vec<PathBuf> = Vec::new();

    collect_recursive(root, &mut files, &mut dirs);
    (files, dirs)
}

fn collect_recursive(dir: &Path, files: &mut Vec<PathBuf>, dirs: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();

        if path.is_dir() {
            if DELPHI_BUILD_DIRS.contains(&name_str.as_ref()) {
                dirs.push(path);
                // Don't recurse into dirs we're already removing
                continue;
            }
            // Skip hidden dirs and .git
            if name_str.starts_with('.') {
                continue;
            }
            collect_recursive(&path, files, dirs);
        } else if path.is_file() {
            if let Some(ext) = path.extension() {
                if DELPHI_EXTENSIONS.contains(&ext.to_string_lossy().as_ref())
                    && !is_git_tracked(&path)
                {
                    files.push(path);
                }
            }
        }
    }
}
